### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by raulanatol** [moiseslodeiro/AnuarGIT_Dev#1]
https://github.com/raulanatol/curso_git_ull_2016/wiki/Reglas-para-puntuar

**Comment by franmorales86** [comment]
:+1: @moiseslodeiro

**Comment by ardielgr** [comment]
:+1: @ManzDev

**Comment by moiseslodeiro** [comment]
:+1: @yodra

**Comment by yodra** [comment]
:+1: @ardielgr
:+1: https://github.com/evilgom/repoAnuario/tree/master

**Comment by jurses** [comment]
:+1: Mejor anuario

**Comment by evilgom** [comment]
:+1: Mejor anuario

**Comment by simonemarin** [comment]
:+1: Mejor anuario

**Comment by Dacoher** [comment]
:+1: Mejor anuario
